import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TasksProvider } from "@/context/TasksContext";
import { ThemeProvider } from "@/context/ThemeContext";
import { ReactNode } from 'react';
import { I18nextProvider } from 'react-i18next';
import i18n from '../i18n';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
}

function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          {/* <I18nextProvider i18n={i18n}> */}
            <TasksProvider>
              {children}
            </TasksProvider>
          {/* </I18nextProvider> */}
        </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout;
